spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #测试用:本地数据库
    url: jdbc:mysql://localhost:3306/auditall?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

    #部署用：连接远程数据库
    #    url: jdbc:mysql://39.106.186.110:3306/auditall?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    #    username: fan
    #    password: "06152022"

    #部署用：阿里云数据库
#    url: jdbc:mysql://rm-bp179ijtwt8jyh5tdio.mysql.rds.aliyuncs.com:3306/auditall?&serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    username: fanmysql
#    password: 06152022sS
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: 593931651@qq.com
    password: mqzumfzoivpobeee
    properties:
      mail:
        smtp:
          socketFactory: class:javax.net.ssl.SSLSocketFactory
          port: 587
    default-encoding: utf-8
    protocol: smtp
  mvc:
    async:
      request-timeout: 60000
  redis:
#    host: 127.0.0.1
    #    host: 39.106.186.110
    host: 101.200.121.0
    port: 6379
    password: 06152022ss


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0



server:
  port: 8800
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    connection-timeout: 18000000
    max-connections: 30000
    max-swallow-size: 100MB
    resource:
      allow-caching: false


dap:
  checkschedules: 0 45 7 * * *
  dateschedules: 0 50 7 * * *

logging:
  file:
    name: auditLog.log
    max-history: 3
  level:
    root: info

selfDefination:
  emailSender: 593931651@qq.com
  validateAddress: http://www.auditall.cn/validate




